apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  input.conf: |
    input {
      tcp {
        port => 5044
        codec => json
      }
    }

    filter {
      json {
        source => "message"
      }
    }

  output.conf: |
    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        manage_template => false
        index => "logstash-local1"
      }
    }