apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: 'sample_monitoring'
        scrape_interval: 15s
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['auth-service:8083']